version: '3.0'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-cassandra"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    # labels:
    #   com.docker-tc.enabled: 1
    # volumes:
    #   - ~/.mytb-data:/data
    #   - ~/.mytb-logs:/var/log/thingsboard
