[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fistexplore"
version = "0.1.0"
dependencies = [
    "numpy >= 1.26.0",
    "pandas >= 2.1.2",
    "matplotlib >= 3.8.1",
]